apiVersion: v1
kind: ServiceAccount
metadata:
  name: logs-controller-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logs-controller-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log" ]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logs-controller-binding
subjects:
  - kind: ServiceAccount
    name: logs-controller-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: logs-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: controller-benchmark
spec:
  template:
    metadata:
      labels:
        app: controller-benchmark
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: false
      serviceAccountName: logs-controller-account
      containers:
        - name: log-rotation
          image: tmazur316/controller-benchmark:1.0
          imagePullPolicy: Always
          command: [ "go", "run", "./benchmark/benchmark1/benchmark1.go" ]
